model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 500
  end_sym: "</s>"
  low_resource: False
  prompt_template: '[INST] {} [/INST]'
  llama_model: "meta-llama/Llama-2-7b-chat-hf"
  ckpt: "/home/ricke/emotion-llama/rep/checkpoints/save_checkpoint/emotion_llama.pth"
  lora_r: 64
  lora_alpha: 16

datasets:    
  feature_face_caption:  #
    batch_size: 1
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 30

evaluation_datasets:

  hcmw_caption:
    eval_file_path: /home/ricke/emotion-llama/feature_extract/labels_HCMW.txt  # Update this path
    img_path: /home/ricke/emotion-llama/feature_extract/clips_nn    
    max_new_tokens: 500
    batch_size: 1

run:
  task: image_text_pretrain
  name: minigptv2_evaluation
  save_path: /home/user/project/Emotion-LLaMA/results
